CREATE DATABASE IF NOT EXISTS motosmart
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE motosmart;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  marca VARCHAR(60) NULL,
  modelo VARCHAR(80) NULL,
  anio SMALLINT UNSIGNED NULL,
  kilometraje INT UNSIGNED NULL DEFAULT 0,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
